name: Update Stock Data
on:
  schedule:
    - cron: '*/30 * * * *'  # Каждые 30 минут
  workflow_dispatch:        # Можно запускать вручную
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install requests
    - name: Run script
      env:
        MOYSKLAD_API_TOKEN: ${{ secrets.MOYSKLAD_API_TOKEN }}
      run: python moysklad.py
    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add stock_data.json
        git commit -m "Auto-update stock data"
        git push
