name: Update Stock Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests gh

      - name: Run Moysklad script
        env:
          MOYSKLAD_API_TOKEN: ${{ secrets.MOYSKLAD_API_TOKEN }}
        run: python moysklad.py

      - name: Commit and push changes
        env:
          GH_TKN: ${{ secrets.GH_TKN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://$GH_TKN@github.com/naumovpandavape/pandavape-stock.git"
          git add stock_data.json
          if git diff --cached --quiet; then
            echo "Нет изменений для коммита."
          else
            git commit -m "Auto-update stock data ($(date +'%Y-%m-%d %H:%M'))"
            git push origin main
          fi

      - name: Update existing Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TKN }}
        run: |
          # Устанавливаем корректный PATH для gh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Проверяем наличие файла с ID Gist
          if [ -f gist_id.txt ]; then
            echo "Обновляем существующий Gist..."
            GIST_ID=$(cat gist_id.txt | tr -d '\n' | tr -d '\r')
            echo "Используем Gist ID: $GIST_ID"
            
            # Проверяем существование Gist
            if gh gist view $GIST_ID >/dev/null 2>&1; then
              gh gist edit $GIST_ID -f stock_data.json --desc "Stock data $(date +'%Y-%m-%d %H:%M')"
              echo "Gist успешно обновлен."
            else
              echo "Gist не найден, создаем новый..."
              GIST_URL=$(gh gist create stock_data.json --public=false --desc "Stock data $(date +'%Y-%m-%d %H:%M')")
              GIST_ID=$(echo $GIST_URL | grep -oP 'gist.github.com/\K[0-9a-f]+')
              echo $GIST_ID > gist_id.txt
              git add gist_id.txt
              git commit -m "Add new Gist ID file"
              git push origin main
            fi
          else
            echo "Создаем новый Gist..."
            GIST_URL=$(gh gist create stock_data.json --public=false --desc "Stock data $(date +'%Y-%m-%d %H:%M')")
            GIST_ID=$(echo $GIST_URL | grep -oP 'gist.github.com/\K[0-9a-f]+')
            echo $GIST_ID > gist_id.txt
            git add gist_id.txt
            git commit -m "Add Gist ID file"
            git push origin main
          fi
          echo "Gist доступен по ссылке: https://gist.github.com/$GIST_ID"
