name: Update Gist with stock data

on:
  schedule:
    - cron: "*/30 * * * *"  # Запуск каждые 30 минут
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  update_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Python script
        env:
          MOYSKLAD_API_TOKEN: ${{ secrets.MOYSKLAD_API_TOKEN }}
        run: python moysklad.py  # Генерируем stock_data.json

      - name: Prepare JSON payload
        run: |
          echo '{"files": {"stock_data.json": {"content": ' > payload.json
          jq -Rs . stock_data.json >> payload.json
          echo '}}}' >> payload.json

      - name: Update Gist
        env:
          GIST_ID: "ba2621f911b6733cad947f820748a192"
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}
        run: |
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          --data "@payload.json"
