name: Update Gist with stock data

on:
  schedule:
    - cron: "*/30 * * * *"  # Запуск каждые 30 минут
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  update_gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Python script
        run: python your_script.py  # Запуск твоего скрипта, который обновляет stock_data.json

      - name: Update Gist
        env:
          GIST_ID: "ba2621f911b6733cad947f820748a192"  # Заменить на ID Gist из URL
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}  # Секретный токен GitHub
        run: |
          CONTENT=$(jq -Rs . < stock_data.json)  # Кодируем JSON в строку
          curl -X PATCH "https://api.github.com/gists/$GIST_ID" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"files\": {\"stock_data.json\": {\"content\": $CONTENT}}}"
