name: Update Stock Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Test Moysklad connection
        run: |
          curl -v -X GET "https://api.moysklad.ru/api/remap/1.2/entity/product" \
          -H "Authorization: Bearer ${{ secrets.MOYSKLAD_API_TOKEN }}" \
          -H "Accept-Encoding: gzip"

      - name: Run Moysklad script
        env:
          MOYSKLAD_API_TOKEN: ${{ secrets.MOYSKLAD_API_TOKEN }}
        run: python moysklad.py

     - name: Commit and push changes
        env:
          GH_TKN: ${{ secrets.GH_TKN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://$GH_TKN@github.com/naumovpandavape/pandavape-stock.git"
          git add stock_data.json
          git commit -m "Auto-update stock data ($(date +'%Y-%m-%d %H:%M'))"
          git push origin main

      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TKN }}
        run: |
          if [ -f gist_id.txt ]; then
            GIST_ID=$(cat gist_id.txt)
            gh gist edit $GIST_ID -f stock_data.json --desc "Stock data $(date +'%Y-%m-%d %H:%M')"
          fi
