name: Update Stock Data

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Moysklad script
        env:
          MOYSKLAD_API_TOKEN: ${{ secrets.MOYSKLAD_API_TOKEN }}
        run: python moysklad.py

      - name: Commit and push changes
        env:
          GH_TKN: ${{ secrets.GH_TKN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:$GH_TKN@github.com/naumovpandavape/pandavape-stock.git"
          git add stock_data.json
          git commit -m "Auto-update stock data ($(date +'%Y-%m-%d %H:%M'))"
          git push origin main

      - name: Update existing Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TKN }}
        run: |
          # Ваш постоянный Gist ID
          GIST_ID="e6c57c6cdf407ca642b0b52e30777f69"
          
          # Обновляем существующий Gist
          gh gist edit $GIST_ID \
            --filename "stock_data.json" \
            --file "stock_data.json" \
            --desc "Stock data $(date +'%Y-%m-%d %H:%M')"
          
          echo "✅ Gist обновлён: https://gist.github.com/$GIST_ID"
